### PR TITLE
Remove unused 'request' dependency

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Maybe I'm missing something but I don't see why it was added in
https://github.com/microsoft/dtslint/commit/3c57139d7e2afa4600846a00123843e85e42083e

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@sanders Friendly ping 👐 
Not blocker in any sense but I would love to remove a bunch of implicit `devDependencies` from my packages.

**Comment by IvanGoncharov** [comment]
@sandersn If possible can you please release it sooner?
Previously it was just my paranoia about number packages in `node_modules` but now I get this message on every `npm install`/`yarn install`:
> warning dtslint > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by sandersn** [comment]
Done, as version 2.0.6.

**Comment by IvanGoncharov** [comment]
@sandersn Thank a lot 👍 
One less warning and 39 fewer potential security vulnerabilities in my `node_modules` folder.

**Pull request merged**
